CREATE TABLE [Log] (
[ID] [int] IDENTITY (1, 1) NOT NULL ,
[SessionID] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
[Level] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL ,
[Logger] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL ,
[Message] [text] COLLATE Chinese_PRC_CI_AS NULL ,
[Exception] [text] COLLATE Chinese_PRC_CI_AS NULL,
[UrlReferrer] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NULL ,
[Url] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NULL ,
[Browser] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL ,
[UserAgent] [varchar] (500) COLLATE Chinese_PRC_CI_AS NULL ,
[ClientIP] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL ,
[MachineName] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL ,
[Thread] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL ,
[Date] [datetime] NOT NULL ,
)
